replace intuita occurrences
codemod-com/docs pull request #65
Opened 2024-01-15 18:05 UTC by mohab-sameh

2024-02-15 21:15 UTC, alexbit-codemod requested changes
was it supposed to be a draft PR?
i just found the issued in the bottom files... there are many small instances of using codemod.com and intuita. lets fix those and lemme know once you are done. thanks

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/cli/advanced-usage.md
> +The `--threadCount` option can be used to specify the number of worker threads Codemod.com uses while running codemods. This option is set to 4 threads by default.
"the CLI engine" uses... not  "Codemod.com"
and in general, lets not use Codemod.com that much... its not neat and not needed. Codemod with capital C is good. and we can use it with platform or team to clarify we are not talking about the codemods with lowercase c.
@mohab-sameh

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/cli/advanced-usage.md
> +The `--useJson` option can be used to switch Codemod.com's CLI responses to JSON format.
the CLI response...

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/cli/advanced-usage.md
> +By default, the Codemod.com CLI excludes the following glob pattern: `--exclude "**/node_modules/**/*.*"`. If you are using a different glob pattern, we recommend excluding the `node_modules` directo
the CLI
no need to repeat company name.

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/cli/advanced-usage.md
> +You can specify your glob patterns to include specific file formats or directory structures. The default pattern Codemod.com CLI uses is: `--include "**/*.*{ts,tsx,js,jsx,mjs,cjs,mdx}"`.
the CLI

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/cli/advanced-usage.md
> +If you want to use Intutia through a graphical interface, check out the [Codemod.com VS Code Extension](/docs/vs-code-extension/quickstart).
?! :D @mohab-sameh

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/about/terms-and-conditions.md
> +  <meta name='og:image' content='https://raw.githubusercontent.com/codemod-com/docs/main/static/img/docs/intuita-docs-opengraph.png'/>
i'm a bit confused here... @mohab-sameh

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/about/telemetry-compliance.md
> +  <meta name='og:image' content='https://raw.githubusercontent.com/codemod-com/docs/main/static/img/docs/intuita-docs-opengraph.png'/>
same here why intuita.

2024-02-15 21:15 UTC, alexbit-codemod commented on docs/about/privacy-policy.md
> +  <meta name='og:image' content='https://raw.githubusercontent.com/codemod-com/docs/main/static/img/docs/intuita-docs-opengraph.png'/>
and here.

2024-02-15 21:15 UTC, alexbit-codemod commented on blog/2023-9-25dream-migration/index.md
> +1. Install **Codemod.com CLI**: `npm i -g intuita`
just say install the CLI. 
also it shold say npm i -g codemod @mohab-sameh

2024-02-15 21:15 UTC, alexbit-codemod commented on blog/2023-9-25dream-migration/index.md
> +While Codemod.com's codemods are very powerful, some project-specific cases might require human intervention.
no need to say codemod.com's codemod! just codemod

2024-02-15 21:15 UTC, alexbit-codemod commented on blog/2023-9-25dream-migration/index.md
> +1. Codemod Discovery panel in Codemod.com's VS Code extension
no need to add .com

2024-02-15 21:15 UTC, alexbit-codemod commented on blog/2023-9-25dream-migration/index.md
> +2. Running the Codemod.com CLI command: intuita list
should say codemod list not intuita

2024-02-16 10:43 UTC, mohab-sameh commented
@alexbit-codemod This is an old and stale PR. I should've closed it a few weeks ago. All the issues here are fixed on `main`.

2024-02-16 10:43 UTC, closed without merging